### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by Qwin**

### CODE REVIEW

**Comment by Qwin** [comment]
@pdesmarets can you have a look at this PR. I updated the docs with details on the plugin.

**Comment by pdesmarets** [comment]
Very nice!  If I may suggest:
- plugin installation steps 2 & 3 can be combined (simplified): there's a menu option Help > DB target plugin manager (we'll change that name to "Plugin manager" in the next release...  Plus renumber steps 4 & 5 into 3 & 4
) what do you mean by "Lastly the Joi objects might need some adjustments as some naming you might have chosen breaks the javascript syntax."  Can't that be fixed with the [Naming Conventions](https://hackolade.com/help/Namingconventions.html) feature?

**Comment by Qwin** [comment]
@pdesmarets I will change the steps, as for the issue with the naming, its more about someone naming an object enterprise.test or New Field, that will cause the joi to be generated like 
var schema = {
    enterprise.test: Joi.string(),
    New Field: Joi.string()
}

Which in javascript properties are not allowed to have a dot or a space. But usually a person will see his mistake right away and change the name of the object.

**Comment by Qwin** [comment]
@pdesmarets made the changes and clarified my object generation line with an example.

**Comment by pdesmarets** [comment]
Looks good to me!  Just one tip, with the Naming Conventions feature, you may have a "Business Name" for entities and attributes that contains spaces, dots, and others, while the "Technical Name"  (aka "code" in the model file) is configured to ignore or replace a list of "invalid characters".  Best of both worlds...

**Pull request merged**
